services:
  database:
    image: postgres:14
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpwd
      POSTGRES_DB: web_II
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: server
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/web_II
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpwd
    volumes:
      - .:/app       # usa seu c√≥digo local dentro do container
      - ~/.m2:/root/.m2
      

  mailhog:
    image: mailhog/mailhog
    container_name: mail
    ports:
      - "1025:1025" 
      - "8025:8025" 


volumes:
  pgdata: